package main

/*
NameMap:map[
boolean:class{name: boolean, id: 4, fields: []}
byte:class{name: byte, id: 8, fields: []}
char:class{name: char, id: 5, fields: []}
datadog.DatadogProfilerClassRefCache:class{name: datadog.DatadogProfilerClassRefCache, id: 124, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:size Type:11 ConstantPool:false Array:false}]}
datadog.DatadogProfilerConfig:class{name: datadog.DatadogProfilerConfig, id: 122, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:duration Type:11 ConstantPool:false Array:false} {Name:eventThread Type:22 ConstantPool:true Array:false} {Name:cpuInterval Type:11 ConstantPool:false Array:false} {Name:wallInterval Type:11 ConstantPool:false Array:false} {Name:allocInterval Type:11 ConstantPool:false Array:false} {Name:memleakInterval Type:11 ConstantPool:false Array:false} {Name:memleakCapacity Type:11 ConstantPool:false Array:false} {Name:memleakTrackPercent Type:11 ConstantPool:false Array:false} {Name:gcGenerations Type:4 ConstantPool:false Array:false} {Name:modeMask Type:10 ConstantPool:false Array:false} {Name:version Type:20 ConstantPool:false Array:false} {Name:cpuEngine Type:20 ConstantPool:false Array:false}]}
datadog.Endpoint:class{name: datadog.Endpoint, id: 119, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:duration Type:11 ConstantPool:false Array:false} {Name:eventThread Type:22 ConstantPool:true Array:false} {Name:stackTrace Type:26 ConstantPool:true Array:false} {Name:endpoint Type:20 ConstantPool:true Array:false} {Name:operation Type:32 ConstantPool:true Array:false} {Name:localRootSpanId Type:11 ConstantPool:false Array:false}]}
datadog.ExecutionSample:class{name: datadog.ExecutionSample, id: 101, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:eventThread Type:22 ConstantPool:true Array:false} {Name:stackTrace Type:26 ConstantPool:true Array:false} {Name:state Type:25 ConstantPool:true Array:false} {Name:mode Type:33 ConstantPool:true Array:false} {Name:weight Type:11 ConstantPool:false Array:false} {Name:spanId Type:11 ConstantPool:false Array:false} {Name:localRootSpanId Type:11 ConstantPool:false Array:false} {Name:_dd.trace.operation Type:32 ConstantPool:true Array:false}]}
datadog.HeapLiveObject:class{name: datadog.HeapLiveObject, id: 105, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:eventThread Type:22 ConstantPool:true Array:false} {Name:stackTrace Type:26 ConstantPool:true Array:false} {Name:objectClass Type:21 ConstantPool:true Array:false} {Name:age Type:11 ConstantPool:false Array:false} {Name:size Type:11 ConstantPool:false Array:false} {Name:weight Type:6 ConstantPool:false Array:false} {Name:spanId Type:11 ConstantPool:false Array:false} {Name:localRootSpanId Type:11 ConstantPool:false Array:false} {Name:_dd.trace.operation Type:32 ConstantPool:true Array:false}]}
datadog.HeapUsage:class{name: datadog.HeapUsage, id: 121, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:size Type:11 ConstantPool:false Array:false} {Name:isLive Type:4 ConstantPool:false Array:false}]}
datadog.MethodSample:class{name: datadog.MethodSample, id: 102, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:eventThread Type:22 ConstantPool:true Array:false} {Name:stackTrace Type:26 ConstantPool:true Array:false} {Name:state Type:25 ConstantPool:true Array:false} {Name:mode Type:33 ConstantPool:true Array:false} {Name:weight Type:11 ConstantPool:false Array:false} {Name:spanId Type:11 ConstantPool:false Array:false} {Name:localRootSpanId Type:11 ConstantPool:false Array:false} {Name:_dd.trace.operation Type:32 ConstantPool:true Array:false}]}
datadog.ObjectSample:class{name: datadog.ObjectSample, id: 103, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:eventThread Type:22 ConstantPool:true Array:false} {Name:stackTrace Type:26 ConstantPool:true Array:false} {Name:objectClass Type:21 ConstantPool:true Array:false} {Name:size Type:11 ConstantPool:false Array:false} {Name:weight Type:6 ConstantPool:false Array:false} {Name:spanId Type:11 ConstantPool:false Array:false} {Name:localRootSpanId Type:11 ConstantPool:false Array:false} {Name:_dd.trace.operation Type:32 ConstantPool:true Array:false}]}
datadog.ProfilerCounter:class{name: datadog.ProfilerCounter, id: 125, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:name Type:34 ConstantPool:false Array:false} {Name:count Type:11 ConstantPool:false Array:false}]}
datadog.ProfilerSetting:class{name: datadog.ProfilerSetting, id: 120, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:duration Type:11 ConstantPool:false Array:false} {Name:eventThread Type:22 ConstantPool:true Array:false} {Name:stackTrace Type:26 ConstantPool:true Array:false} {Name:name Type:20 ConstantPool:false Array:false} {Name:value Type:20 ConstantPool:false Array:false} {Name:unit Type:20 ConstantPool:false Array:false}]}
datadog.QueueTime:class{name: datadog.QueueTime, id: 123, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:duration Type:11 ConstantPool:false Array:false} {Name:eventThread Type:22 ConstantPool:true Array:false} {Name:origin Type:22 ConstantPool:true Array:false} {Name:task Type:21 ConstantPool:true Array:false} {Name:scheduler Type:21 ConstantPool:true Array:false} {Name:spanId Type:11 ConstantPool:false Array:false} {Name:localRootSpanId Type:11 ConstantPool:false Array:false} {Name:_dd.trace.operation Type:32 ConstantPool:true Array:false}]}
datadog.WallClockSamplingEpoch:class{name: datadog.WallClockSamplingEpoch, id: 118, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:duration Type:11 ConstantPool:false Array:false} {Name:samplePoolSize Type:10 ConstantPool:false Array:false} {Name:numSuccessfulSamples Type:10 ConstantPool:false Array:false} {Name:numFailedSamples Type:10 ConstantPool:false Array:false} {Name:numExitedThreads Type:10 ConstantPool:false Array:false} {Name:numPermissionDenied Type:10 ConstantPool:false Array:false}]}
datadog.types.ExecutionMode:class{name: datadog.types.ExecutionMode, id: 33, fields: [{Name:name Type:20 ConstantPool:false Array:false}]}
double:class{name: double, id: 7, fields: []}
float:class{name: float, id: 6, fields: []}
int:class{name: int, id: 10, fields: []}
java.lang.Class:class{name: java.lang.Class, id: 21, fields: [{Name:classLoader Type:23 ConstantPool:true Array:false} {Name:name Type:30 ConstantPool:true Array:false} {Name:package Type:29 ConstantPool:true Array:false} {Name:modifiers Type:10 ConstantPool:false Array:false}]}
java.lang.String:class{name: java.lang.String, id: 20, fields: []}
java.lang.Thread:class{name: java.lang.Thread, id: 22, fields: [{Name:osName Type:20 ConstantPool:false Array:false} {Name:osThreadId Type:11 ConstantPool:false Array:false} {Name:javaName Type:20 ConstantPool:false Array:false} {Name:javaThreadId Type:11 ConstantPool:false Array:false}]}
jdk.ActiveRecording:class{name: jdk.ActiveRecording, id: 109, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:duration Type:11 ConstantPool:false Array:false} {Name:eventThread Type:22 ConstantPool:true Array:false} {Name:stackTrace Type:26 ConstantPool:true Array:false} {Name:id Type:11 ConstantPool:false Array:false} {Name:name Type:20 ConstantPool:false Array:false} {Name:destination Type:20 ConstantPool:false Array:false} {Name:maxAge Type:11 ConstantPool:false Array:false} {Name:flushInterval Type:11 ConstantPool:false Array:false} {Name:maxSize Type:11 ConstantPool:false Array:false} {Name:recordingStart Type:11 ConstantPool:false Array:false} {Name:recordingDuration Type:11 ConstantPool:false Array:false}]}
jdk.ActiveSetting:class{name: jdk.ActiveSetting, id: 110, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:duration Type:11 ConstantPool:false Array:false} {Name:eventThread Type:22 ConstantPool:true Array:false} {Name:stackTrace Type:26 ConstantPool:true Array:false} {Name:id Type:11 ConstantPool:false Array:false} {Name:name Type:20 ConstantPool:false Array:false} {Name:value Type:20 ConstantPool:false Array:false}]}
jdk.CPUInformation:class{name: jdk.CPUInformation, id: 112, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:cpu Type:20 ConstantPool:false Array:false} {Name:description Type:20 ConstantPool:false Array:false} {Name:sockets Type:10 ConstantPool:false Array:false} {Name:cores Type:10 ConstantPool:false Array:false} {Name:hwThreads Type:10 ConstantPool:false Array:false}]}
jdk.CPULoad:class{name: jdk.CPULoad, id: 108, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:jvmUser Type:6 ConstantPool:false Array:false} {Name:jvmSystem Type:6 ConstantPool:false Array:false} {Name:machineTotal Type:6 ConstantPool:false Array:false}]}
jdk.InitialSystemProperty:class{name: jdk.InitialSystemProperty, id: 115, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:key Type:20 ConstantPool:false Array:false} {Name:value Type:20 ConstantPool:false Array:false}]}
jdk.JVMInformation:class{name: jdk.JVMInformation, id: 114, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:jvmName Type:20 ConstantPool:false Array:false} {Name:jvmVersion Type:20 ConstantPool:false Array:false} {Name:jvmArguments Type:20 ConstantPool:false Array:false} {Name:jvmFlags Type:20 ConstantPool:false Array:false} {Name:javaArguments Type:20 ConstantPool:false Array:false} {Name:jvmStartTime Type:11 ConstantPool:false Array:false} {Name:pid Type:11 ConstantPool:false Array:false}]}
jdk.NativeLibrary:class{name: jdk.NativeLibrary, id: 116, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:name Type:20 ConstantPool:false Array:false} {Name:baseAddress Type:11 ConstantPool:false Array:false} {Name:topAddress Type:11 ConstantPool:false Array:false}]}
jdk.OSInformation:class{name: jdk.OSInformation, id: 111, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:osVersion Type:20 ConstantPool:false Array:false}]}
jdk.jfr.Category:class{name: jdk.jfr.Category, id: 202, fields: [{Name:value Type:20 ConstantPool:false Array:true}]}
jdk.jfr.DataAmount:class{name: jdk.jfr.DataAmount, id: 205, fields: [{Name:value Type:20 ConstantPool:false Array:false}]}
jdk.jfr.Label:class{name: jdk.jfr.Label, id: 201, fields: [{Name:value Type:20 ConstantPool:false Array:false}]}
jdk.jfr.MemoryAddress:class{name: jdk.jfr.MemoryAddress, id: 206, fields: []}
jdk.jfr.Percentage:class{name: jdk.jfr.Percentage, id: 208, fields: []}
jdk.jfr.Timespan:class{name: jdk.jfr.Timespan, id: 204, fields: [{Name:value Type:20 ConstantPool:false Array:false}]}
jdk.jfr.Timestamp:class{name: jdk.jfr.Timestamp, id: 203, fields: [{Name:value Type:20 ConstantPool:false Array:false}]}
jdk.jfr.Unsigned:class{name: jdk.jfr.Unsigned, id: 207, fields: []}
jdk.types.ClassLoader:class{name: jdk.types.ClassLoader, id: 23, fields: [{Name:type Type:21 ConstantPool:true Array:false} {Name:name Type:30 ConstantPool:true Array:false}]}
jdk.types.FrameType:class{name: jdk.types.FrameType, id: 24, fields: [{Name:description Type:20 ConstantPool:false Array:false}]}
jdk.types.Method:class{name: jdk.types.Method, id: 28, fields: [{Name:type Type:21 ConstantPool:true Array:false} {Name:name Type:30 ConstantPool:true Array:false} {Name:descriptor Type:30 ConstantPool:true Array:false} {Name:modifiers Type:10 ConstantPool:false Array:false} {Name:hidden Type:4 ConstantPool:false Array:false}]}
jdk.types.Package:class{name: jdk.types.Package, id: 29, fields: [{Name:name Type:30 ConstantPool:true Array:false}]}
jdk.types.StackFrame:class{name: jdk.types.StackFrame, id: 27, fields: [{Name:method Type:28 ConstantPool:true Array:false} {Name:lineNumber Type:10 ConstantPool:false Array:false} {Name:bytecodeIndex Type:10 ConstantPool:false Array:false} {Name:type Type:24 ConstantPool:true Array:false}]}
jdk.types.StackTrace:class{name: jdk.types.StackTrace, id: 26, fields: [{Name:truncated Type:4 ConstantPool:false Array:false} {Name:frames Type:27 ConstantPool:false Array:true}]}
jdk.types.Symbol:class{name: jdk.types.Symbol, id: 30, fields: [{Name:string Type:20 ConstantPool:false Array:false}]}
jdk.types.ThreadState:class{name: jdk.types.ThreadState, id: 25, fields: [{Name:name Type:20 ConstantPool:false Array:false}]}
long:class{name: long, id: 11, fields: []}
profiler.Log:class{name: profiler.Log, id: 117, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:level Type:31 ConstantPool:true Array:false} {Name:message Type:20 ConstantPool:false Array:false}]}
profiler.types.AttributeValue:class{name: profiler.types.AttributeValue, id: 32, fields: [{Name:value Type:20 ConstantPool:false Array:false}]}
profiler.types.CounterName:class{name: profiler.types.CounterName, id: 34, fields: [{Name:value Type:20 ConstantPool:false Array:false}]}
profiler.types.LogLevel:class{name: profiler.types.LogLevel, id: 31, fields: [{Name:name Type:20 ConstantPool:false Array:false}]}
short:class{name: short, id: 9, fields: []}]
T_STRING:20 T_INT:10 T_LONG:11 T_FLOAT:6 T_BOOLEAN:4 T_CLASS:21 T_THREAD:22 T_FRAME_TYPE:24 T_THREAD_STATE:25 T_STACK_TRACE:26 T_METHOD:28 T_PACKAGE:29 T_SYMBOL:30 T_LOG_LEVEL:31 T_STACK_FRAME:27 T_CLASS_LOADER:23 T_EXECUTION_SAMPLE:-1
Datadog_ExecutionSample:0 T_WALL_CLOCK_SAMPLE:-1 T_ALLOC_IN_NEW_TLAB:-1 T_ALLOC_OUTSIDE_TLAB:-1 T_ALLOC_SAMPLE:-1 T_LIVE_OBJECT:-1 T_MONITOR_ENTER:-1 T_THREAD_PARK:-1 T_ACTIVE_SETTING:110 T_MALLOC:-1 T_FREE:-1 ISO8859_1Decoder:0xc00045e000}mutex

*/
