package main

/*
class{name: jdk.ThreadStart, id: 2, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:thread Type:162 ConstantPool:true Array:false} {Name:parentThread Type:162 ConstantPool:true Array:false}]}
class{name: jdk.ThreadEnd, id: 3, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:thread Type:162 ConstantPool:true Array:false}]}
class{name: jdk.ThreadSleep, id: 4, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:time Type:204 ConstantPool:false Array:false}]}
class{name: jdk.ThreadPark, id: 5, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:parkedClass Type:164 ConstantPool:true Array:false} {Name:timeout Type:204 ConstantPool:false Array:false} {Name:until Type:204 ConstantPool:false Array:false} {Name:address Type:204 ConstantPool:false Array:false}]}
class{name: jdk.JavaMonitorEnter, id: 6, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:monitorClass Type:164 ConstantPool:true Array:false} {Name:previousOwner Type:162 ConstantPool:true Array:false} {Name:address Type:204 ConstantPool:false Array:false}]}
class{name: jdk.JavaMonitorWait, id: 7, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:monitorClass Type:164 ConstantPool:true Array:false} {Name:notifier Type:162 ConstantPool:true Array:false} {Name:timeout Type:204 ConstantPool:false Array:false} {Name:timedOut Type:210 ConstantPool:false Array:false} {Name:address Type:204 ConstantPool:false Array:false}]}
class{name: jdk.JavaMonitorInflate, id: 8, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:monitorClass Type:164 ConstantPool:true Array:false} {Name:address Type:204 ConstantPool:false Array:false} {Name:cause Type:183 ConstantPool:true Array:false}]}
class{name: jdk.SyncOnValueBasedClass, id: 9, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:valueBasedClass Type:164 ConstantPool:true Array:false}]}
class{name: jdk.BiasedLockRevocation, id: 10, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:lockClass Type:164 ConstantPool:true Array:false} {Name:safepointId Type:204 ConstantPool:false Array:false} {Name:previousOwner Type:162 ConstantPool:true Array:false}]}
class{name: jdk.BiasedLockSelfRevocation, id: 11, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:lockClass Type:164 ConstantPool:true Array:false}]}
class{name: jdk.BiasedLockClassRevocation, id: 12, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:revokedClass Type:164 ConstantPool:true Array:false} {Name:disableBiasing Type:210 ConstantPool:false Array:false} {Name:safepointId Type:204 ConstantPool:false Array:false}]}
class{name: jdk.ReservedStackActivation, id: 13, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:method Type:166 ConstantPool:true Array:false}]}
class{name: jdk.ClassLoad, id: 14, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:loadedClass Type:164 ConstantPool:true Array:false} {Name:definingClassLoader Type:165 ConstantPool:true Array:false} {Name:initiatingClassLoader Type:165 ConstantPool:true Array:false}]}
class{name: jdk.ClassDefine, id: 15, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:definedClass Type:164 ConstantPool:true Array:false} {Name:definingClassLoader Type:165 ConstantPool:true Array:false}]}
class{name: jdk.ClassRedefinition, id: 16, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:redefinedClass Type:164 ConstantPool:true Array:false} {Name:classModificationCount Type:205 ConstantPool:false Array:false} {Name:redefinitionId Type:204 ConstantPool:false Array:false}]}
class{name: jdk.RedefineClasses, id: 17, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:classCount Type:205 ConstantPool:false Array:false} {Name:redefinitionId Type:204 ConstantPool:false Array:false}]}
class{name: jdk.RetransformClasses, id: 18, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:classCount Type:205 ConstantPool:false Array:false} {Name:redefinitionId Type:204 ConstantPool:false Array:false}]}
class{name: jdk.ClassUnload, id: 19, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:unloadedClass Type:164 ConstantPool:true Array:false} {Name:definingClassLoader Type:165 ConstantPool:true Array:false}]}
class{name: jdk.IntFlagChanged, id: 20, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false} {Name:oldValue Type:205 ConstantPool:false Array:false} {Name:newValue Type:205 ConstantPool:false Array:false} {Name:origin Type:181 ConstantPool:true Array:false}]}
class{name: jdk.UnsignedIntFlagChanged, id: 21, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false} {Name:oldValue Type:205 ConstantPool:false Array:false} {Name:newValue Type:205 ConstantPool:false Array:false} {Name:origin Type:181 ConstantPool:true Array:false}]}
class{name: jdk.LongFlagChanged, id: 22, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false} {Name:oldValue Type:204 ConstantPool:false Array:false} {Name:newValue Type:204 ConstantPool:false Array:false} {Name:origin Type:181 ConstantPool:true Array:false}]}
class{name: jdk.UnsignedLongFlagChanged, id: 23, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false} {Name:oldValue Type:204 ConstantPool:false Array:false} {Name:newValue Type:204 ConstantPool:false Array:false} {Name:origin Type:181 ConstantPool:true Array:false}]}
class{name: jdk.DoubleFlagChanged, id: 24, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false} {Name:oldValue Type:208 ConstantPool:false Array:false} {Name:newValue Type:208 ConstantPool:false Array:false} {Name:origin Type:181 ConstantPool:true Array:false}]}
class{name: jdk.BooleanFlagChanged, id: 25, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false} {Name:oldValue Type:210 ConstantPool:false Array:false} {Name:newValue Type:210 ConstantPool:false Array:false} {Name:origin Type:181 ConstantPool:true Array:false}]}
class{name: jdk.StringFlagChanged, id: 26, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false} {Name:oldValue Type:212 ConstantPool:false Array:false} {Name:newValue Type:212 ConstantPool:false Array:false} {Name:origin Type:181 ConstantPool:true Array:false}]}
class{name: jdk.GCHeapSummary, id: 27, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:when Type:171 ConstantPool:true Array:false} {Name:heapSpace Type:147 ConstantPool:false Array:false} {Name:heapUsed Type:204 ConstantPool:false Array:false}]}
class{name: jdk.MetaspaceSummary, id: 28, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:when Type:171 ConstantPool:true Array:false} {Name:gcThreshold Type:204 ConstantPool:false Array:false} {Name:metaspace Type:149 ConstantPool:false Array:false} {Name:dataSpace Type:149 ConstantPool:false Array:false} {Name:classSpace Type:149 ConstantPool:false Array:false}]}
class{name: jdk.MetaspaceGCThreshold, id: 29, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:oldValue Type:204 ConstantPool:false Array:false} {Name:newValue Type:204 ConstantPool:false Array:false} {Name:updater Type:174 ConstantPool:true Array:false}]}
class{name: jdk.MetaspaceAllocationFailure, id: 30, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:classLoader Type:165 ConstantPool:true Array:false} {Name:hiddenClassLoader Type:210 ConstantPool:false Array:false} {Name:size Type:204 ConstantPool:false Array:false} {Name:metadataType Type:176 ConstantPool:true Array:false} {Name:metaspaceObjectType Type:177 ConstantPool:true Array:false}]}
class{name: jdk.MetaspaceOOM, id: 31, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:classLoader Type:165 ConstantPool:true Array:false} {Name:hiddenClassLoader Type:210 ConstantPool:false Array:false} {Name:size Type:204 ConstantPool:false Array:false} {Name:metadataType Type:176 ConstantPool:true Array:false} {Name:metaspaceObjectType Type:177 ConstantPool:true Array:false}]}
class{name: jdk.MetaspaceChunkFreeListSummary, id: 32, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:when Type:171 ConstantPool:true Array:false} {Name:metadataType Type:176 ConstantPool:true Array:false} {Name:specializedChunks Type:204 ConstantPool:false Array:false} {Name:specializedChunksTotalSize Type:204 ConstantPool:false Array:false} {Name:smallChunks Type:204 ConstantPool:false Array:false} {Name:smallChunksTotalSize Type:204 ConstantPool:false Array:false} {Name:mediumChunks Type:204 ConstantPool:false Array:false} {Name:mediumChunksTotalSize Type:204 ConstantPool:false Array:false} {Name:humongousChunks Type:204 ConstantPool:false Array:false} {Name:humongousChunksTotalSize Type:204 ConstantPool:false Array:false}]}
class{name: jdk.PSHeapSummary, id: 33, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:when Type:171 ConstantPool:true Array:false} {Name:oldSpace Type:147 ConstantPool:false Array:false} {Name:oldObjectSpace Type:148 ConstantPool:false Array:false} {Name:youngSpace Type:147 ConstantPool:false Array:false} {Name:edenSpace Type:148 ConstantPool:false Array:false} {Name:fromSpace Type:148 ConstantPool:false Array:false} {Name:toSpace Type:148 ConstantPool:false Array:false}]}
class{name: jdk.G1HeapSummary, id: 34, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:when Type:171 ConstantPool:true Array:false} {Name:edenUsedSize Type:204 ConstantPool:false Array:false} {Name:edenTotalSize Type:204 ConstantPool:false Array:false} {Name:survivorUsedSize Type:204 ConstantPool:false Array:false} {Name:numberOfRegions Type:205 ConstantPool:false Array:false}]}
class{name: jdk.GarbageCollection, id: 35, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:name Type:169 ConstantPool:true Array:false} {Name:cause Type:170 ConstantPool:true Array:false} {Name:sumOfPauses Type:204 ConstantPool:false Array:false} {Name:longestPause Type:204 ConstantPool:false Array:false}]}
class{name: jdk.SystemGC, id: 36, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:invokedConcurrent Type:210 ConstantPool:false Array:false}]}
class{name: jdk.ParallelOldGarbageCollection, id: 37, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:densePrefix Type:204 ConstantPool:false Array:false}]}
class{name: jdk.YoungGarbageCollection, id: 38, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:tenuringThreshold Type:205 ConstantPool:false Array:false}]}
class{name: jdk.OldGarbageCollection, id: 39, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:gcId Type:205 ConstantPool:false Array:false}]}
class{name: jdk.G1GarbageCollection, id: 40, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:type Type:173 ConstantPool:true Array:false}]}
class{name: jdk.G1MMU, id: 41, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:timeSlice Type:204 ConstantPool:false Array:false} {Name:gcTime Type:204 ConstantPool:false Array:false} {Name:pauseTarget Type:204 ConstantPool:false Array:false}]}
class{name: jdk.EvacuationInformation, id: 42, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:cSetRegions Type:205 ConstantPool:false Array:false} {Name:cSetUsedBefore Type:204 ConstantPool:false Array:false} {Name:cSetUsedAfter Type:204 ConstantPool:false Array:false} {Name:allocationRegions Type:205 ConstantPool:false Array:false} {Name:allocationRegionsUsedBefore Type:204 ConstantPool:false Array:false} {Name:allocationRegionsUsedAfter Type:204 ConstantPool:false Array:false} {Name:bytesCopied Type:204 ConstantPool:false Array:false} {Name:regionsFreed Type:205 ConstantPool:false Array:false}]}
class{name: jdk.GCReferenceStatistics, id: 43, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:type Type:175 ConstantPool:true Array:false} {Name:count Type:204 ConstantPool:false Array:false}]}
class{name: jdk.ObjectCountAfterGC, id: 44, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:objectClass Type:164 ConstantPool:true Array:false} {Name:count Type:204 ConstantPool:false Array:false} {Name:totalSize Type:204 ConstantPool:false Array:false}]}
class{name: jdk.G1EvacuationYoungStatistics, id: 45, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:statistics Type:151 ConstantPool:false Array:false}]}
class{name: jdk.G1EvacuationOldStatistics, id: 46, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:statistics Type:151 ConstantPool:false Array:false}]}
class{name: jdk.G1BasicIHOP, id: 47, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:threshold Type:204 ConstantPool:false Array:false} {Name:thresholdPercentage Type:209 ConstantPool:false Array:false} {Name:targetOccupancy Type:204 ConstantPool:false Array:false} {Name:currentOccupancy Type:204 ConstantPool:false Array:false} {Name:recentMutatorAllocationSize Type:204 ConstantPool:false Array:false} {Name:recentMutatorDuration Type:204 ConstantPool:false Array:false} {Name:recentAllocationRate Type:208 ConstantPool:false Array:false} {Name:lastMarkingDuration Type:204 ConstantPool:false Array:false}]}
class{name: jdk.G1AdaptiveIHOP, id: 48, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:threshold Type:204 ConstantPool:false Array:false} {Name:thresholdPercentage Type:209 ConstantPool:false Array:false} {Name:ihopTargetOccupancy Type:204 ConstantPool:false Array:false} {Name:currentOccupancy Type:204 ConstantPool:false Array:false} {Name:additionalBufferSize Type:204 ConstantPool:false Array:false} {Name:predictedAllocationRate Type:208 ConstantPool:false Array:false} {Name:predictedMarkingDuration Type:204 ConstantPool:false Array:false} {Name:predictionActive Type:210 ConstantPool:false Array:false}]}
class{name: jdk.PromoteObjectInNewPLAB, id: 49, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:objectClass Type:164 ConstantPool:true Array:false} {Name:objectSize Type:204 ConstantPool:false Array:false} {Name:tenuringAge Type:205 ConstantPool:false Array:false} {Name:tenured Type:210 ConstantPool:false Array:false} {Name:plabSize Type:204 ConstantPool:false Array:false}]}
class{name: jdk.PromoteObjectOutsidePLAB, id: 50, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:objectClass Type:164 ConstantPool:true Array:false} {Name:objectSize Type:204 ConstantPool:false Array:false} {Name:tenuringAge Type:205 ConstantPool:false Array:false} {Name:tenured Type:210 ConstantPool:false Array:false}]}
class{name: jdk.PromotionFailed, id: 51, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:promotionFailed Type:150 ConstantPool:false Array:false} {Name:thread Type:162 ConstantPool:true Array:false}]}
class{name: jdk.EvacuationFailed, id: 52, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:evacuationFailed Type:150 ConstantPool:false Array:false}]}
class{name: jdk.ConcurrentModeFailure, id: 53, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:gcId Type:205 ConstantPool:false Array:false}]}
class{name: jdk.GCPhasePause, id: 54, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false}]}
class{name: jdk.GCPhasePauseLevel1, id: 55, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false}]}
class{name: jdk.GCPhasePauseLevel2, id: 56, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false}]}
class{name: jdk.GCPhasePauseLevel3, id: 57, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false}]}
class{name: jdk.GCPhasePauseLevel4, id: 58, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false}]}
class{name: jdk.GCPhaseConcurrent, id: 59, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false}]}
class{name: jdk.GCPhaseConcurrentLevel1, id: 60, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false}]}
class{name: jdk.GCPhaseParallel, id: 61, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:gcWorkerId Type:205 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false}]}
class{name: jdk.AllocationRequiringGC, id: 62, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:size Type:204 ConstantPool:false Array:false}]}
class{name: jdk.TenuringDistribution, id: 63, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:age Type:205 ConstantPool:false Array:false} {Name:size Type:204 ConstantPool:false Array:false}]}
class{name: jdk.G1HeapRegionTypeChange, id: 64, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:index Type:205 ConstantPool:false Array:false} {Name:from Type:172 ConstantPool:true Array:false} {Name:to Type:172 ConstantPool:true Array:false} {Name:start Type:204 ConstantPool:false Array:false} {Name:used Type:204 ConstantPool:false Array:false}]}
class{name: jdk.Compilation, id: 65, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:compileId Type:205 ConstantPool:false Array:false} {Name:compiler Type:157 ConstantPool:true Array:false} {Name:method Type:166 ConstantPool:true Array:false} {Name:compileLevel Type:206 ConstantPool:false Array:false} {Name:succeded Type:210 ConstantPool:false Array:false} {Name:isOsr Type:210 ConstantPool:false Array:false} {Name:codeSize Type:204 ConstantPool:false Array:false} {Name:inlinedBytes Type:204 ConstantPool:false Array:false}]}
class{name: jdk.CompilerPhase, id: 66, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:phase Type:180 ConstantPool:true Array:false} {Name:compileId Type:205 ConstantPool:false Array:false} {Name:phaseLevel Type:206 ConstantPool:false Array:false}]}
class{name: jdk.CompilationFailure, id: 67, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:failureMessage Type:212 ConstantPool:false Array:false} {Name:compileId Type:205 ConstantPool:false Array:false}]}
class{name: jdk.CompilerInlining, id: 68, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:compileId Type:205 ConstantPool:false Array:false} {Name:caller Type:166 ConstantPool:true Array:false} {Name:callee Type:152 ConstantPool:false Array:false} {Name:succeeded Type:210 ConstantPool:false Array:false} {Name:message Type:212 ConstantPool:false Array:false} {Name:bci Type:205 ConstantPool:false Array:false}]}
class{name: jdk.SweepCodeCache, id: 69, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:sweepId Type:205 ConstantPool:false Array:false} {Name:sweptCount Type:205 ConstantPool:false Array:false} {Name:flushedCount Type:205 ConstantPool:false Array:false} {Name:zombifiedCount Type:205 ConstantPool:false Array:false}]}
class{name: jdk.CodeCacheFull, id: 70, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:codeBlobType Type:182 ConstantPool:true Array:false} {Name:startAddress Type:204 ConstantPool:false Array:false} {Name:commitedTopAddress Type:204 ConstantPool:false Array:false} {Name:reservedTopAddress Type:204 ConstantPool:false Array:false} {Name:entryCount Type:205 ConstantPool:false Array:false} {Name:methodCount Type:205 ConstantPool:false Array:false} {Name:adaptorCount Type:205 ConstantPool:false Array:false} {Name:unallocatedCapacity Type:204 ConstantPool:false Array:false} {Name:fullCount Type:205 ConstantPool:false Array:false}]}
class{name: jdk.Deoptimization, id: 71, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:compileId Type:205 ConstantPool:false Array:false} {Name:compiler Type:157 ConstantPool:true Array:false} {Name:method Type:166 ConstantPool:true Array:false} {Name:lineNumber Type:205 ConstantPool:false Array:false} {Name:bci Type:205 ConstantPool:false Array:false} {Name:instruction Type:156 ConstantPool:true Array:false} {Name:reason Type:154 ConstantPool:true Array:false} {Name:action Type:155 ConstantPool:true Array:false}]}
class{name: jdk.SafepointBegin, id: 72, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:safepointId Type:204 ConstantPool:false Array:false} {Name:totalThreadCount Type:205 ConstantPool:false Array:false} {Name:jniCriticalThreadCount Type:205 ConstantPool:false Array:false}]}
class{name: jdk.SafepointStateSynchronization, id: 73, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:safepointId Type:204 ConstantPool:false Array:false} {Name:initialThreadCount Type:205 ConstantPool:false Array:false} {Name:runningThreadCount Type:205 ConstantPool:false Array:false} {Name:iterations Type:205 ConstantPool:false Array:false}]}
class{name: jdk.SafepointCleanup, id: 74, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:safepointId Type:204 ConstantPool:false Array:false}]}
class{name: jdk.SafepointCleanupTask, id: 75, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:safepointId Type:204 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false}]}
class{name: jdk.SafepointEnd, id: 76, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:safepointId Type:204 ConstantPool:false Array:false}]}
class{name: jdk.ExecuteVMOperation, id: 77, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:operation Type:179 ConstantPool:true Array:false} {Name:safepoint Type:210 ConstantPool:false Array:false} {Name:blocking Type:210 ConstantPool:false Array:false} {Name:caller Type:162 ConstantPool:true Array:false} {Name:safepointId Type:204 ConstantPool:false Array:false}]}
class{name: jdk.Shutdown, id: 78, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:reason Type:212 ConstantPool:false Array:false}]}
class{name: jdk.ObjectAllocationInNewTLAB, id: 79, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:objectClass Type:164 ConstantPool:true Array:false} {Name:allocationSize Type:204 ConstantPool:false Array:false} {Name:tlabSize Type:204 ConstantPool:false Array:false}]}
class{name: jdk.ObjectAllocationOutsideTLAB, id: 80, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:objectClass Type:164 ConstantPool:true Array:false} {Name:allocationSize Type:204 ConstantPool:false Array:false}]}
class{name: jdk.ObjectAllocationSample, id: 81, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:objectClass Type:164 ConstantPool:true Array:false} {Name:weight Type:204 ConstantPool:false Array:false}]}
class{name: jdk.OldObjectSample, id: 82, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:allocationTime Type:204 ConstantPool:false Array:false} {Name:objectAge Type:204 ConstantPool:false Array:false} {Name:lastKnownHeapUsage Type:204 ConstantPool:false Array:false} {Name:object Type:193 ConstantPool:true Array:false} {Name:arrayElements Type:205 ConstantPool:false Array:false} {Name:root Type:190 ConstantPool:true Array:false}]}
class{name: jdk.DumpReason, id: 83, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:reason Type:212 ConstantPool:false Array:false} {Name:recordingId Type:205 ConstantPool:false Array:false}]}
class{name: jdk.DataLoss, id: 84, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:amount Type:204 ConstantPool:false Array:false} {Name:total Type:204 ConstantPool:false Array:false}]}
class{name: jdk.JVMInformation, id: 85, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:jvmName Type:212 ConstantPool:false Array:false} {Name:jvmVersion Type:212 ConstantPool:false Array:false} {Name:jvmArguments Type:212 ConstantPool:false Array:false} {Name:jvmFlags Type:212 ConstantPool:false Array:false} {Name:javaArguments Type:212 ConstantPool:false Array:false} {Name:jvmStartTime Type:204 ConstantPool:false Array:false} {Name:pid Type:204 ConstantPool:false Array:false}]}
class{name: jdk.OSInformation, id: 86, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:osVersion Type:212 ConstantPool:false Array:false}]}
class{name: jdk.VirtualizationInformation, id: 87, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false}]}
class{name: jdk.InitialSystemProperty, id: 88, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:key Type:212 ConstantPool:false Array:false} {Name:value Type:212 ConstantPool:false Array:false}]}
class{name: jdk.InitialEnvironmentVariable, id: 89, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:key Type:212 ConstantPool:false Array:false} {Name:value Type:212 ConstantPool:false Array:false}]}
class{name: jdk.SystemProcess, id: 90, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:pid Type:212 ConstantPool:false Array:false} {Name:commandLine Type:212 ConstantPool:false Array:false}]}
class{name: jdk.CPUInformation, id: 91, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:cpu Type:212 ConstantPool:false Array:false} {Name:description Type:212 ConstantPool:false Array:false} {Name:sockets Type:205 ConstantPool:false Array:false} {Name:cores Type:205 ConstantPool:false Array:false} {Name:hwThreads Type:205 ConstantPool:false Array:false}]}
class{name: jdk.CPUTimeStampCounter, id: 92, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:fastTimeEnabled Type:210 ConstantPool:false Array:false} {Name:fastTimeAutoEnabled Type:210 ConstantPool:false Array:false} {Name:osFrequency Type:204 ConstantPool:false Array:false} {Name:fastTimeFrequency Type:204 ConstantPool:false Array:false}]}
class{name: jdk.CPULoad, id: 93, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:jvmUser Type:209 ConstantPool:false Array:false} {Name:jvmSystem Type:209 ConstantPool:false Array:false} {Name:machineTotal Type:209 ConstantPool:false Array:false}]}
class{name: jdk.ThreadCPULoad, id: 94, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:user Type:209 ConstantPool:false Array:false} {Name:system Type:209 ConstantPool:false Array:false}]}
class{name: jdk.ThreadContextSwitchRate, id: 95, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:switchRate Type:209 ConstantPool:false Array:false}]}
class{name: jdk.NetworkUtilization, id: 96, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:networkInterface Type:161 ConstantPool:true Array:false} {Name:readRate Type:204 ConstantPool:false Array:false} {Name:writeRate Type:204 ConstantPool:false Array:false}]}
class{name: jdk.JavaThreadStatistics, id: 97, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:activeCount Type:204 ConstantPool:false Array:false} {Name:daemonCount Type:204 ConstantPool:false Array:false} {Name:accumulatedCount Type:204 ConstantPool:false Array:false} {Name:peakCount Type:204 ConstantPool:false Array:false}]}
class{name: jdk.ClassLoadingStatistics, id: 98, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:loadedClassCount Type:204 ConstantPool:false Array:false} {Name:unloadedClassCount Type:204 ConstantPool:false Array:false}]}
class{name: jdk.ClassLoaderStatistics, id: 99, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:classLoader Type:165 ConstantPool:true Array:false} {Name:parentClassLoader Type:165 ConstantPool:true Array:false} {Name:classLoaderData Type:204 ConstantPool:false Array:false} {Name:classCount Type:204 ConstantPool:false Array:false} {Name:chunkSize Type:204 ConstantPool:false Array:false} {Name:blockSize Type:204 ConstantPool:false Array:false} {Name:hiddenClassCount Type:204 ConstantPool:false Array:false} {Name:hiddenChunkSize Type:204 ConstantPool:false Array:false} {Name:hiddenBlockSize Type:204 ConstantPool:false Array:false}]}
class{name: jdk.SymbolTableStatistics, id: 100, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:bucketCount Type:204 ConstantPool:false Array:false} {Name:entryCount Type:204 ConstantPool:false Array:false} {Name:totalFootprint Type:204 ConstantPool:false Array:false} {Name:bucketCountMaximum Type:204 ConstantPool:false Array:false} {Name:bucketCountAverage Type:209 ConstantPool:false Array:false} {Name:bucketCountVariance Type:209 ConstantPool:false Array:false} {Name:bucketCountStandardDeviation Type:209 ConstantPool:false Array:false} {Name:insertionRate Type:209 ConstantPool:false Array:false} {Name:removalRate Type:209 ConstantPool:false Array:false}]}
class{name: jdk.StringTableStatistics, id: 101, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:bucketCount Type:204 ConstantPool:false Array:false} {Name:entryCount Type:204 ConstantPool:false Array:false} {Name:totalFootprint Type:204 ConstantPool:false Array:false} {Name:bucketCountMaximum Type:204 ConstantPool:false Array:false} {Name:bucketCountAverage Type:209 ConstantPool:false Array:false} {Name:bucketCountVariance Type:209 ConstantPool:false Array:false} {Name:bucketCountStandardDeviation Type:209 ConstantPool:false Array:false} {Name:insertionRate Type:209 ConstantPool:false Array:false} {Name:removalRate Type:209 ConstantPool:false Array:false}]}
class{name: jdk.PlaceholderTableStatistics, id: 102, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:bucketCount Type:204 ConstantPool:false Array:false} {Name:entryCount Type:204 ConstantPool:false Array:false} {Name:totalFootprint Type:204 ConstantPool:false Array:false} {Name:bucketCountMaximum Type:204 ConstantPool:false Array:false} {Name:bucketCountAverage Type:209 ConstantPool:false Array:false} {Name:bucketCountVariance Type:209 ConstantPool:false Array:false} {Name:bucketCountStandardDeviation Type:209 ConstantPool:false Array:false} {Name:insertionRate Type:209 ConstantPool:false Array:false} {Name:removalRate Type:209 ConstantPool:false Array:false}]}
class{name: jdk.LoaderConstraintsTableStatistics, id: 103, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:bucketCount Type:204 ConstantPool:false Array:false} {Name:entryCount Type:204 ConstantPool:false Array:false} {Name:totalFootprint Type:204 ConstantPool:false Array:false} {Name:bucketCountMaximum Type:204 ConstantPool:false Array:false} {Name:bucketCountAverage Type:209 ConstantPool:false Array:false} {Name:bucketCountVariance Type:209 ConstantPool:false Array:false} {Name:bucketCountStandardDeviation Type:209 ConstantPool:false Array:false} {Name:insertionRate Type:209 ConstantPool:false Array:false} {Name:removalRate Type:209 ConstantPool:false Array:false}]}
class{name: jdk.ProtectionDomainCacheTableStatistics, id: 104, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:bucketCount Type:204 ConstantPool:false Array:false} {Name:entryCount Type:204 ConstantPool:false Array:false} {Name:totalFootprint Type:204 ConstantPool:false Array:false} {Name:bucketCountMaximum Type:204 ConstantPool:false Array:false} {Name:bucketCountAverage Type:209 ConstantPool:false Array:false} {Name:bucketCountVariance Type:209 ConstantPool:false Array:false} {Name:bucketCountStandardDeviation Type:209 ConstantPool:false Array:false} {Name:insertionRate Type:209 ConstantPool:false Array:false} {Name:removalRate Type:209 ConstantPool:false Array:false}]}
class{name: jdk.ThreadAllocationStatistics, id: 105, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:allocated Type:204 ConstantPool:false Array:false} {Name:thread Type:162 ConstantPool:true Array:false}]}
class{name: jdk.PhysicalMemory, id: 106, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:totalSize Type:204 ConstantPool:false Array:false} {Name:usedSize Type:204 ConstantPool:false Array:false}]}
class{name: jdk.ExecutionSample, id: 107, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:sampledThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:state Type:168 ConstantPool:true Array:false}]}
class{name: jdk.NativeMethodSample, id: 108, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:sampledThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:state Type:168 ConstantPool:true Array:false}]}
class{name: jdk.ThreadDump, id: 109, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:result Type:212 ConstantPool:false Array:false}]}
class{name: jdk.NativeLibrary, id: 110, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false} {Name:baseAddress Type:204 ConstantPool:false Array:false} {Name:topAddress Type:204 ConstantPool:false Array:false}]}
class{name: jdk.ModuleRequire, id: 111, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:source Type:184 ConstantPool:true Array:false} {Name:requiredModule Type:184 ConstantPool:true Array:false}]}
class{name: jdk.ModuleExport, id: 112, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:exportedPackage Type:185 ConstantPool:true Array:false} {Name:targetModule Type:184 ConstantPool:true Array:false}]}
class{name: jdk.CompilerStatistics, id: 113, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:compileCount Type:205 ConstantPool:false Array:false} {Name:bailoutCount Type:205 ConstantPool:false Array:false} {Name:invalidatedCount Type:205 ConstantPool:false Array:false} {Name:osrCompileCount Type:205 ConstantPool:false Array:false} {Name:standardCompileCount Type:205 ConstantPool:false Array:false} {Name:osrBytesCompiled Type:204 ConstantPool:false Array:false} {Name:standardBytesCompiled Type:204 ConstantPool:false Array:false} {Name:nmethodsSize Type:204 ConstantPool:false Array:false} {Name:nmethodCodeSize Type:204 ConstantPool:false Array:false} {Name:peakTimeSpent Type:204 ConstantPool:false Array:false} {Name:totalTimeSpent Type:204 ConstantPool:false Array:false}]}
class{name: jdk.CompilerConfiguration, id: 114, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:threadCount Type:205 ConstantPool:false Array:false} {Name:tieredCompilation Type:210 ConstantPool:false Array:false}]}
class{name: jdk.CodeCacheStatistics, id: 115, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:codeBlobType Type:182 ConstantPool:true Array:false} {Name:startAddress Type:204 ConstantPool:false Array:false} {Name:reservedTopAddress Type:204 ConstantPool:false Array:false} {Name:entryCount Type:205 ConstantPool:false Array:false} {Name:methodCount Type:205 ConstantPool:false Array:false} {Name:adaptorCount Type:205 ConstantPool:false Array:false} {Name:unallocatedCapacity Type:204 ConstantPool:false Array:false} {Name:fullCount Type:205 ConstantPool:false Array:false}]}
class{name: jdk.CodeCacheConfiguration, id: 116, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:initialSize Type:204 ConstantPool:false Array:false} {Name:reservedSize Type:204 ConstantPool:false Array:false} {Name:nonNMethodSize Type:204 ConstantPool:false Array:false} {Name:profiledSize Type:204 ConstantPool:false Array:false} {Name:nonProfiledSize Type:204 ConstantPool:false Array:false} {Name:expansionSize Type:204 ConstantPool:false Array:false} {Name:minBlockLength Type:204 ConstantPool:false Array:false} {Name:startAddress Type:204 ConstantPool:false Array:false} {Name:reservedTopAddress Type:204 ConstantPool:false Array:false}]}
class{name: jdk.CodeSweeperStatistics, id: 117, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:sweepCount Type:205 ConstantPool:false Array:false} {Name:methodReclaimedCount Type:205 ConstantPool:false Array:false} {Name:totalSweepTime Type:204 ConstantPool:false Array:false} {Name:peakFractionTime Type:204 ConstantPool:false Array:false} {Name:peakSweepTime Type:204 ConstantPool:false Array:false}]}
class{name: jdk.CodeSweeperConfiguration, id: 118, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:sweeperEnabled Type:210 ConstantPool:false Array:false} {Name:flushingEnabled Type:210 ConstantPool:false Array:false} {Name:sweepThreshold Type:204 ConstantPool:false Array:false}]}
class{name: jdk.IntFlag, id: 119, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false} {Name:value Type:205 ConstantPool:false Array:false} {Name:origin Type:181 ConstantPool:true Array:false}]}
class{name: jdk.UnsignedIntFlag, id: 120, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false} {Name:value Type:205 ConstantPool:false Array:false} {Name:origin Type:181 ConstantPool:true Array:false}]}
class{name: jdk.LongFlag, id: 121, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false} {Name:value Type:204 ConstantPool:false Array:false} {Name:origin Type:181 ConstantPool:true Array:false}]}
class{name: jdk.UnsignedLongFlag, id: 122, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false} {Name:value Type:204 ConstantPool:false Array:false} {Name:origin Type:181 ConstantPool:true Array:false}]}
class{name: jdk.DoubleFlag, id: 123, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false} {Name:value Type:208 ConstantPool:false Array:false} {Name:origin Type:181 ConstantPool:true Array:false}]}
class{name: jdk.BooleanFlag, id: 124, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false} {Name:value Type:210 ConstantPool:false Array:false} {Name:origin Type:181 ConstantPool:true Array:false}]}
class{name: jdk.StringFlag, id: 125, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false} {Name:value Type:212 ConstantPool:false Array:false} {Name:origin Type:181 ConstantPool:true Array:false}]}
class{name: jdk.ObjectCount, id: 126, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:objectClass Type:164 ConstantPool:true Array:false} {Name:count Type:204 ConstantPool:false Array:false} {Name:totalSize Type:204 ConstantPool:false Array:false}]}
class{name: jdk.G1HeapRegionInformation, id: 127, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:index Type:205 ConstantPool:false Array:false} {Name:type Type:172 ConstantPool:true Array:false} {Name:start Type:204 ConstantPool:false Array:false} {Name:used Type:204 ConstantPool:false Array:false}]}
class{name: jdk.GCConfiguration, id: 128, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:youngCollector Type:169 ConstantPool:true Array:false} {Name:oldCollector Type:169 ConstantPool:true Array:false} {Name:parallelGCThreads Type:205 ConstantPool:false Array:false} {Name:concurrentGCThreads Type:205 ConstantPool:false Array:false} {Name:usesDynamicGCThreads Type:210 ConstantPool:false Array:false} {Name:isExplicitGCConcurrent Type:210 ConstantPool:false Array:false} {Name:isExplicitGCDisabled Type:210 ConstantPool:false Array:false} {Name:pauseTarget Type:204 ConstantPool:false Array:false} {Name:gcTimeRatio Type:205 ConstantPool:false Array:false}]}
class{name: jdk.GCSurvivorConfiguration, id: 129, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:maxTenuringThreshold Type:207 ConstantPool:false Array:false} {Name:initialTenuringThreshold Type:207 ConstantPool:false Array:false}]}
class{name: jdk.GCTLABConfiguration, id: 130, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:usesTLABs Type:210 ConstantPool:false Array:false} {Name:minTLABSize Type:204 ConstantPool:false Array:false} {Name:tlabRefillWasteLimit Type:204 ConstantPool:false Array:false}]}
class{name: jdk.GCHeapConfiguration, id: 131, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:minSize Type:204 ConstantPool:false Array:false} {Name:maxSize Type:204 ConstantPool:false Array:false} {Name:initialSize Type:204 ConstantPool:false Array:false} {Name:usesCompressedOops Type:210 ConstantPool:false Array:false} {Name:compressedOopsMode Type:178 ConstantPool:true Array:false} {Name:objectAlignment Type:204 ConstantPool:false Array:false} {Name:heapAddressBits Type:207 ConstantPool:false Array:false}]}
class{name: jdk.YoungGenerationConfiguration, id: 132, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:minSize Type:204 ConstantPool:false Array:false} {Name:maxSize Type:204 ConstantPool:false Array:false} {Name:newRatio Type:205 ConstantPool:false Array:false}]}
class{name: jdk.ZAllocationStall, id: 133, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:type Type:158 ConstantPool:true Array:false} {Name:size Type:204 ConstantPool:false Array:false}]}
class{name: jdk.ZPageAllocation, id: 134, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:type Type:158 ConstantPool:true Array:false} {Name:size Type:204 ConstantPool:false Array:false} {Name:flushed Type:204 ConstantPool:false Array:false} {Name:committed Type:204 ConstantPool:false Array:false} {Name:segments Type:205 ConstantPool:false Array:false} {Name:nonBlocking Type:210 ConstantPool:false Array:false}]}
class{name: jdk.ZRelocationSet, id: 135, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:total Type:204 ConstantPool:false Array:false} {Name:empty Type:204 ConstantPool:false Array:false} {Name:relocate Type:204 ConstantPool:false Array:false}]}
class{name: jdk.ZRelocationSetGroup, id: 136, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:type Type:158 ConstantPool:true Array:false} {Name:pages Type:204 ConstantPool:false Array:false} {Name:total Type:204 ConstantPool:false Array:false} {Name:empty Type:204 ConstantPool:false Array:false} {Name:relocate Type:204 ConstantPool:false Array:false}]}
class{name: jdk.ZStatisticsCounter, id: 137, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:id Type:159 ConstantPool:true Array:false} {Name:increment Type:204 ConstantPool:false Array:false} {Name:value Type:204 ConstantPool:false Array:false}]}
class{name: jdk.ZStatisticsSampler, id: 138, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:id Type:160 ConstantPool:true Array:false} {Name:value Type:204 ConstantPool:false Array:false}]}
class{name: jdk.ZThreadPhase, id: 139, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:gcId Type:205 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false}]}
class{name: jdk.ZUncommit, id: 140, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:uncommitted Type:204 ConstantPool:false Array:false}]}
class{name: jdk.ZUnmap, id: 141, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:unmapped Type:204 ConstantPool:false Array:false}]}
class{name: jdk.ShenandoahHeapRegionStateChange, id: 142, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:index Type:205 ConstantPool:false Array:false} {Name:from Type:153 ConstantPool:true Array:false} {Name:to Type:153 ConstantPool:true Array:false} {Name:start Type:204 ConstantPool:false Array:false} {Name:used Type:204 ConstantPool:false Array:false}]}
class{name: jdk.ShenandoahHeapRegionInformation, id: 143, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:index Type:205 ConstantPool:false Array:false} {Name:state Type:153 ConstantPool:true Array:false} {Name:start Type:204 ConstantPool:false Array:false} {Name:used Type:204 ConstantPool:false Array:false}]}
class{name: jdk.Flush, id: 144, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:flushId Type:204 ConstantPool:false Array:false} {Name:elements Type:204 ConstantPool:false Array:false} {Name:size Type:204 ConstantPool:false Array:false}]}
class{name: jdk.HeapDump, id: 145, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:destination Type:212 ConstantPool:false Array:false} {Name:size Type:204 ConstantPool:false Array:false} {Name:gcBeforeDump Type:210 ConstantPool:false Array:false} {Name:onOutOfMemoryError Type:210 ConstantPool:false Array:false}]}
class{name: jdk.GCLocker, id: 146, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:lockCount Type:205 ConstantPool:false Array:false} {Name:stallCount Type:205 ConstantPool:false Array:false}]}
class{name: jdk.types.VirtualSpace, id: 147, fields: [{Name:start Type:204 ConstantPool:false Array:false} {Name:committedEnd Type:204 ConstantPool:false Array:false} {Name:committedSize Type:204 ConstantPool:false Array:false} {Name:reservedEnd Type:204 ConstantPool:false Array:false} {Name:reservedSize Type:204 ConstantPool:false Array:false}]}
class{name: jdk.types.ObjectSpace, id: 148, fields: [{Name:start Type:204 ConstantPool:false Array:false} {Name:end Type:204 ConstantPool:false Array:false} {Name:used Type:204 ConstantPool:false Array:false} {Name:size Type:204 ConstantPool:false Array:false}]}
class{name: jdk.types.MetaspaceSizes, id: 149, fields: [{Name:committed Type:204 ConstantPool:false Array:false} {Name:used Type:204 ConstantPool:false Array:false} {Name:reserved Type:204 ConstantPool:false Array:false}]}
class{name: jdk.types.CopyFailed, id: 150, fields: [{Name:objectCount Type:204 ConstantPool:false Array:false} {Name:firstSize Type:204 ConstantPool:false Array:false} {Name:smallestSize Type:204 ConstantPool:false Array:false} {Name:totalSize Type:204 ConstantPool:false Array:false}]}
class{name: jdk.types.G1EvacuationStatistics, id: 151, fields: [{Name:gcId Type:205 ConstantPool:false Array:false} {Name:allocated Type:204 ConstantPool:false Array:false} {Name:wasted Type:204 ConstantPool:false Array:false} {Name:used Type:204 ConstantPool:false Array:false} {Name:undoWaste Type:204 ConstantPool:false Array:false} {Name:regionEndWaste Type:204 ConstantPool:false Array:false} {Name:regionsRefilled Type:205 ConstantPool:false Array:false} {Name:directAllocated Type:204 ConstantPool:false Array:false} {Name:failureUsed Type:204 ConstantPool:false Array:false} {Name:failureWaste Type:204 ConstantPool:false Array:false}]}
class{name: jdk.types.CalleeMethod, id: 152, fields: [{Name:type Type:212 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false} {Name:descriptor Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.ShenandoahHeapRegionState, id: 153, fields: [{Name:state Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.DeoptimizationReason, id: 154, fields: [{Name:reason Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.DeoptimizationAction, id: 155, fields: [{Name:action Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.Bytecode, id: 156, fields: [{Name:bytecode Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.CompilerType, id: 157, fields: [{Name:compiler Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.ZPageTypeType, id: 158, fields: [{Name:type Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.ZStatisticsCounterType, id: 159, fields: [{Name:counter Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.ZStatisticsSamplerType, id: 160, fields: [{Name:sampler Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.NetworkInterfaceName, id: 161, fields: [{Name:networkInterface Type:212 ConstantPool:false Array:false}]}
class{name: java.lang.Thread, id: 162, fields: [{Name:osName Type:212 ConstantPool:false Array:false} {Name:osThreadId Type:204 ConstantPool:false Array:false} {Name:javaName Type:212 ConstantPool:false Array:false} {Name:javaThreadId Type:204 ConstantPool:false Array:false} {Name:group Type:163 ConstantPool:true Array:false}]}
class{name: jdk.types.ThreadGroup, id: 163, fields: [{Name:parent Type:163 ConstantPool:true Array:false} {Name:name Type:212 ConstantPool:false Array:false}]}
class{name: java.lang.Class, id: 164, fields: [{Name:classLoader Type:165 ConstantPool:true Array:false} {Name:name Type:167 ConstantPool:true Array:false} {Name:package Type:185 ConstantPool:true Array:false} {Name:modifiers Type:205 ConstantPool:false Array:false} {Name:hidden Type:210 ConstantPool:false Array:false}]}
class{name: jdk.types.ClassLoader, id: 165, fields: [{Name:type Type:164 ConstantPool:true Array:false} {Name:name Type:167 ConstantPool:true Array:false}]}
class{name: jdk.types.Method, id: 166, fields: [{Name:type Type:164 ConstantPool:true Array:false} {Name:name Type:167 ConstantPool:true Array:false} {Name:descriptor Type:167 ConstantPool:true Array:false} {Name:modifiers Type:205 ConstantPool:false Array:false} {Name:hidden Type:210 ConstantPool:false Array:false}]}
class{name: jdk.types.Symbol, id: 167, fields: [{Name:string Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.ThreadState, id: 168, fields: [{Name:name Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.GCName, id: 169, fields: [{Name:name Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.GCCause, id: 170, fields: [{Name:cause Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.GCWhen, id: 171, fields: [{Name:when Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.G1HeapRegionType, id: 172, fields: [{Name:type Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.G1YCType, id: 173, fields: [{Name:type Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.GCThresholdUpdater, id: 174, fields: [{Name:updater Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.ReferenceType, id: 175, fields: [{Name:type Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.MetadataType, id: 176, fields: [{Name:type Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.MetaspaceObjectType, id: 177, fields: [{Name:type Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.NarrowOopMode, id: 178, fields: [{Name:mode Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.VMOperationType, id: 179, fields: [{Name:type Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.CompilerPhaseType, id: 180, fields: [{Name:phase Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.FlagValueOrigin, id: 181, fields: [{Name:origin Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.CodeBlobType, id: 182, fields: [{Name:type Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.InflateCause, id: 183, fields: [{Name:cause Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.Module, id: 184, fields: [{Name:name Type:167 ConstantPool:true Array:false} {Name:version Type:167 ConstantPool:true Array:false} {Name:location Type:167 ConstantPool:true Array:false} {Name:classLoader Type:165 ConstantPool:true Array:false}]}
class{name: jdk.types.Package, id: 185, fields: [{Name:name Type:167 ConstantPool:true Array:false} {Name:module Type:184 ConstantPool:true Array:false} {Name:exported Type:210 ConstantPool:false Array:false}]}
class{name: jdk.types.StackTrace, id: 186, fields: [{Name:truncated Type:210 ConstantPool:false Array:false} {Name:frames Type:195 ConstantPool:false Array:true}]}
class{name: jdk.types.FrameType, id: 187, fields: [{Name:description Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.OldObjectRootSystem, id: 188, fields: [{Name:system Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.OldObjectRootType, id: 189, fields: [{Name:type Type:212 ConstantPool:false Array:false}]}
class{name: jdk.types.OldObjectGcRoot, id: 190, fields: [{Name:description Type:212 ConstantPool:false Array:false} {Name:system Type:188 ConstantPool:true Array:false} {Name:type Type:189 ConstantPool:true Array:false}]}
class{name: jdk.types.OldObjectArray, id: 191, fields: [{Name:size Type:205 ConstantPool:false Array:false} {Name:index Type:205 ConstantPool:false Array:false}]}
class{name: jdk.types.OldObjectField, id: 192, fields: [{Name:name Type:212 ConstantPool:false Array:false} {Name:modifiers Type:206 ConstantPool:false Array:false}]}
class{name: jdk.types.OldObject, id: 193, fields: [{Name:address Type:204 ConstantPool:false Array:false} {Name:type Type:164 ConstantPool:true Array:false} {Name:description Type:212 ConstantPool:false Array:false} {Name:referrer Type:194 ConstantPool:true Array:false}]}
class{name: jdk.types.Reference, id: 194, fields: [{Name:array Type:191 ConstantPool:true Array:false} {Name:field Type:192 ConstantPool:true Array:false} {Name:object Type:193 ConstantPool:true Array:false} {Name:skip Type:205 ConstantPool:false Array:false}]}
class{name: jdk.types.StackFrame, id: 195, fields: [{Name:method Type:166 ConstantPool:true Array:false} {Name:lineNumber Type:205 ConstantPool:false Array:false} {Name:bytecodeIndex Type:205 ConstantPool:false Array:false} {Name:type Type:187 ConstantPool:true Array:false}]}
class{name: jdk.types.ChunkHeader, id: 196, fields: [{Name:payload Type:207 ConstantPool:false Array:true}]}
class{name: jdk.types.JavaMonitorAddress, id: 197, fields: []}
class{name: jdk.types.SafepointId, id: 198, fields: []}
class{name: jdk.types.GcId, id: 199, fields: []}
class{name: jdk.types.CompileId, id: 200, fields: []}
class{name: jdk.types.SweepId, id: 201, fields: []}
class{name: jdk.types.FlushId, id: 202, fields: []}
class{name: jdk.types.ClassRedefinitionId, id: 203, fields: []}
class{name: long, id: 204, fields: []}
class{name: int, id: 205, fields: []}
class{name: short, id: 206, fields: []}
class{name: byte, id: 207, fields: []}
class{name: double, id: 208, fields: []}
class{name: float, id: 209, fields: []}
class{name: boolean, id: 210, fields: []}
class{name: char, id: 211, fields: []}
class{name: java.lang.String, id: 212, fields: []}
class{name: datadog.ExceptionSample, id: 5818, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:type Type:212 ConstantPool:false Array:false} {Name:message Type:212 ConstantPool:false Array:false} {Name:sampled Type:210 ConstantPool:false Array:false} {Name:firstOccurrence Type:210 ConstantPool:false Array:false} {Name:localRootSpanId Type:204 ConstantPool:false Array:false} {Name:spanId Type:204 ConstantPool:false Array:false}]}
class{name: jdk.jfr.Label, id: 5832, fields: [{Name:value Type:212 ConstantPool:false Array:false}]}
class{name: jdk.jfr.Threshold, id: 5834, fields: [{Name:value Type:212 ConstantPool:false Array:false}]}
class{name: jdk.jfr.StackTrace, id: 5835, fields: [{Name:value Type:210 ConstantPool:false Array:false}]}
class{name: jdk.jfr.Period, id: 5836, fields: [{Name:value Type:212 ConstantPool:false Array:false}]}
class{name: jdk.jfr.Enabled, id: 5838, fields: [{Name:value Type:210 ConstantPool:false Array:false}]}
class{name: jdk.jfr.Name, id: 5844, fields: [{Name:value Type:212 ConstantPool:false Array:false}]}
class{name: jdk.jfr.Timespan, id: 5850, fields: [{Name:value Type:212 ConstantPool:false Array:false}]}
class{name: jdk.jfr.ContentType, id: 5851, fields: []}
class{name: jdk.jfr.Description, id: 5852, fields: [{Name:value Type:212 ConstantPool:false Array:false}]}
class{name: jdk.jfr.Timestamp, id: 5865, fields: [{Name:value Type:212 ConstantPool:false Array:false}]}
class{name: jdk.jfr.Relational, id: 5877, fields: []}
class{name: jdk.jfr.TransitionTo, id: 5880, fields: []}
class{name: jdk.jfr.TransitionFrom, id: 5882, fields: []}
class{name: jdk.jfr.Experimental, id: 5884, fields: []}
class{name: jdk.jfr.Unsigned, id: 5887, fields: []}
class{name: jdk.jfr.Category, id: 5888, fields: [{Name:value Type:212 ConstantPool:false Array:true}]}
class{name: jdk.jfr.internal.Throttle, id: 5892, fields: [{Name:value Type:212 ConstantPool:false Array:false}]}
class{name: jdk.jfr.internal.Cutoff, id: 5893, fields: [{Name:value Type:212 ConstantPool:false Array:false}]}
class{name: jdk.jfr.MemoryAddress, id: 5894, fields: []}
class{name: jdk.jfr.DataAmount, id: 5895, fields: [{Name:value Type:212 ConstantPool:false Array:false}]}
class{name: jdk.jfr.Percentage, id: 5897, fields: []}
class{name: jdk.jfr.Frequency, id: 5898, fields: []}
class{name: jdk.settings.Enabled, id: 5908, fields: []}
class{name: jdk.jfr.BooleanFlag, id: 5910, fields: []}
class{name: jdk.settings.Threshold, id: 5912, fields: []}
class{name: jdk.settings.StackTrace, id: 5914, fields: []}
class{name: jdk.settings.Period, id: 5917, fields: []}
class{name: jdk.settings.Cutoff, id: 5918, fields: []}
class{name: jdk.settings.Throttle, id: 5919, fields: []}
class{name: datadog.ExceptionCount, id: 5967, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:type Type:212 ConstantPool:false Array:false} {Name:count Type:204 ConstantPool:false Array:false}]}
class{name: datadog.DirectAllocationTotal, id: 5972, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:allocatingClass Type:212 ConstantPool:false Array:false} {Name:source Type:212 ConstantPool:false Array:false} {Name:allocated Type:204 ConstantPool:false Array:false}]}
class{name: datadog.AvailableProcessorCores, id: 5977, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:availableProcessorCores Type:205 ConstantPool:false Array:false}]}
class{name: datadog.Deadlock, id: 14241, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:id Type:204 ConstantPool:false Array:false} {Name:threadCount Type:205 ConstantPool:false Array:false}]}
class{name: datadog.DeadlockedThread, id: 14252, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:threadId Type:204 ConstantPool:false Array:false} {Name:threadName Type:212 ConstantPool:false Array:false} {Name:lockName Type:212 ConstantPool:false Array:false} {Name:lockOwnerThreadName Type:212 ConstantPool:false Array:false} {Name:lockOwnerThreadId Type:204 ConstantPool:false Array:false} {Name:lockingFrame Type:212 ConstantPool:false Array:false} {Name:waitingFrame Type:212 ConstantPool:false Array:false} {Name:id Type:204 ConstantPool:false Array:false}]}
class{name: datadog.SmapEntry, id: 14262, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:startAddress Type:204 ConstantPool:false Array:false} {Name:endAddress Type:204 ConstantPool:false Array:false} {Name:perms Type:212 ConstantPool:false Array:false} {Name:offset Type:204 ConstantPool:false Array:false} {Name:dev Type:212 ConstantPool:false Array:false} {Name:inodeID Type:205 ConstantPool:false Array:false} {Name:pathname Type:212 ConstantPool:false Array:false} {Name:size Type:204 ConstantPool:false Array:false} {Name:kernelPageSize Type:204 ConstantPool:false Array:false} {Name:mmuPageSize Type:204 ConstantPool:false Array:false} {Name:rss Type:204 ConstantPool:false Array:false} {Name:pss Type:204 ConstantPool:false Array:false} {Name:pssDirty Type:204 ConstantPool:false Array:false} {Name:sharedClean Type:204 ConstantPool:false Array:false} {Name:sharedDirty Type:204 ConstantPool:false Array:false} {Name:privateClean Type:204 ConstantPool:false Array:false} {Name:privateDirty Type:204 ConstantPool:false Array:false} {Name:referenced Type:204 ConstantPool:false Array:false} {Name:anonymous Type:204 ConstantPool:false Array:false} {Name:ksm Type:204 ConstantPool:false Array:false} {Name:lazyFree Type:204 ConstantPool:false Array:false} {Name:anonHugePages Type:204 ConstantPool:false Array:false} {Name:shmemPmdMapped Type:204 ConstantPool:false Array:false} {Name:filePmdMapped Type:204 ConstantPool:false Array:false} {Name:sharedHugetlb Type:204 ConstantPool:false Array:false} {Name:privateHugetlb Type:204 ConstantPool:false Array:false} {Name:swap Type:204 ConstantPool:false Array:false} {Name:swapPss Type:204 ConstantPool:false Array:false} {Name:locked Type:204 ConstantPool:false Array:false} {Name:thpEligible Type:210 ConstantPool:false Array:false} {Name:vmFlags Type:212 ConstantPool:false Array:false} {Name:encounteredForeignKeys Type:210 ConstantPool:false Array:false} {Name:nmtCategory Type:212 ConstantPool:false Array:false}]}
class{name: datadog.AggregatedSmapEntry, id: 14282, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:nmtCategory Type:212 ConstantPool:false Array:false} {Name:rss Type:204 ConstantPool:false Array:false}]}
class{name: jdk.FileForce, id: 14637, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:path Type:212 ConstantPool:false Array:false} {Name:metaData Type:210 ConstantPool:false Array:false}]}
class{name: jdk.FileRead, id: 14639, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:path Type:212 ConstantPool:false Array:false} {Name:bytesRead Type:204 ConstantPool:false Array:false} {Name:endOfFile Type:210 ConstantPool:false Array:false}]}
class{name: jdk.FileWrite, id: 14641, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:path Type:212 ConstantPool:false Array:false} {Name:bytesWritten Type:204 ConstantPool:false Array:false}]}
class{name: jdk.SocketRead, id: 14643, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:host Type:212 ConstantPool:false Array:false} {Name:address Type:212 ConstantPool:false Array:false} {Name:port Type:205 ConstantPool:false Array:false} {Name:timeout Type:204 ConstantPool:false Array:false} {Name:bytesRead Type:204 ConstantPool:false Array:false} {Name:endOfStream Type:210 ConstantPool:false Array:false}]}
class{name: jdk.SocketWrite, id: 14645, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:host Type:212 ConstantPool:false Array:false} {Name:address Type:212 ConstantPool:false Array:false} {Name:port Type:205 ConstantPool:false Array:false} {Name:bytesWritten Type:204 ConstantPool:false Array:false}]}
class{name: jdk.JavaExceptionThrow, id: 14647, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:message Type:212 ConstantPool:false Array:false} {Name:thrownClass Type:164 ConstantPool:true Array:false}]}
class{name: jdk.ExceptionStatistics, id: 14649, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:throwables Type:204 ConstantPool:false Array:false}]}
class{name: jdk.JavaErrorThrow, id: 14651, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:message Type:212 ConstantPool:false Array:false} {Name:thrownClass Type:164 ConstantPool:true Array:false}]}
class{name: jdk.ActiveSetting, id: 14653, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:id Type:204 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false} {Name:value Type:212 ConstantPool:false Array:false}]}
class{name: jdk.ActiveRecording, id: 14655, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:id Type:204 ConstantPool:false Array:false} {Name:name Type:212 ConstantPool:false Array:false} {Name:destination Type:212 ConstantPool:false Array:false} {Name:maxAge Type:204 ConstantPool:false Array:false} {Name:flushInterval Type:204 ConstantPool:false Array:false} {Name:maxSize Type:204 ConstantPool:false Array:false} {Name:recordingStart Type:204 ConstantPool:false Array:false} {Name:recordingDuration Type:204 ConstantPool:false Array:false}]}
class{name: jdk.Deserialization, id: 14657, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:filterConfigured Type:210 ConstantPool:false Array:false} {Name:filterStatus Type:212 ConstantPool:false Array:false} {Name:type Type:164 ConstantPool:true Array:false} {Name:arrayLength Type:205 ConstantPool:false Array:false} {Name:objectReferences Type:204 ConstantPool:false Array:false} {Name:depth Type:204 ConstantPool:false Array:false} {Name:bytesRead Type:204 ConstantPool:false Array:false} {Name:exceptionType Type:164 ConstantPool:true Array:false} {Name:exceptionMessage Type:212 ConstantPool:false Array:false}]}
class{name: jdk.ProcessStart, id: 14659, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:pid Type:204 ConstantPool:false Array:false} {Name:directory Type:212 ConstantPool:false Array:false} {Name:command Type:212 ConstantPool:false Array:false}]}
class{name: jdk.SecurityPropertyModification, id: 14661, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:key Type:212 ConstantPool:false Array:false} {Name:value Type:212 ConstantPool:false Array:false}]}
class{name: jdk.TLSHandshake, id: 14663, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:peerHost Type:212 ConstantPool:false Array:false} {Name:peerPort Type:205 ConstantPool:false Array:false} {Name:protocolVersion Type:212 ConstantPool:false Array:false} {Name:cipherSuite Type:212 ConstantPool:false Array:false} {Name:certificateId Type:204 ConstantPool:false Array:false}]}
class{name: jdk.X509Certificate, id: 14665, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:algorithm Type:212 ConstantPool:false Array:false} {Name:serialNumber Type:212 ConstantPool:false Array:false} {Name:subject Type:212 ConstantPool:false Array:false} {Name:issuer Type:212 ConstantPool:false Array:false} {Name:keyType Type:212 ConstantPool:false Array:false} {Name:keyLength Type:205 ConstantPool:false Array:false} {Name:certificateId Type:204 ConstantPool:false Array:false} {Name:validFrom Type:204 ConstantPool:false Array:false} {Name:validUntil Type:204 ConstantPool:false Array:false}]}
class{name: jdk.X509Validation, id: 14667, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:certificateId Type:204 ConstantPool:false Array:false} {Name:certificatePosition Type:205 ConstantPool:false Array:false} {Name:validationCounter Type:204 ConstantPool:false Array:false}]}
class{name: jdk.DirectBufferStatistics, id: 14670, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:maxCapacity Type:204 ConstantPool:false Array:false} {Name:count Type:204 ConstantPool:false Array:false} {Name:totalCapacity Type:204 ConstantPool:false Array:false} {Name:memoryUsed Type:204 ConstantPool:false Array:false}]}
class{name: jdk.InitialSecurityProperty, id: 14672, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:key Type:212 ConstantPool:false Array:false} {Name:value Type:212 ConstantPool:false Array:false}]}
class{name: jdk.ContainerConfiguration, id: 14721, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:containerType Type:212 ConstantPool:false Array:false} {Name:cpuSlicePeriod Type:204 ConstantPool:false Array:false} {Name:cpuQuota Type:204 ConstantPool:false Array:false} {Name:cpuShares Type:204 ConstantPool:false Array:false} {Name:effectiveCpuCount Type:204 ConstantPool:false Array:false} {Name:memorySoftLimit Type:204 ConstantPool:false Array:false} {Name:memoryLimit Type:204 ConstantPool:false Array:false} {Name:swapMemoryLimit Type:204 ConstantPool:false Array:false}]}
class{name: jdk.ContainerCPUUsage, id: 14724, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:cpuTime Type:204 ConstantPool:false Array:false} {Name:cpuUserTime Type:204 ConstantPool:false Array:false} {Name:cpuSystemTime Type:204 ConstantPool:false Array:false}]}
class{name: jdk.ContainerCPUThrottling, id: 14727, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:cpuElapsedSlices Type:204 ConstantPool:false Array:false} {Name:cpuThrottledSlices Type:204 ConstantPool:false Array:false} {Name:cpuThrottledTime Type:204 ConstantPool:false Array:false}]}
class{name: jdk.ContainerMemoryUsage, id: 14730, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:memoryFailCount Type:204 ConstantPool:false Array:false} {Name:memoryUsage Type:204 ConstantPool:false Array:false} {Name:swapMemoryUsage Type:204 ConstantPool:false Array:false}]}
class{name: jdk.ContainerIOUsage, id: 14733, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:serviceRequests Type:204 ConstantPool:false Array:false} {Name:dataTransferred Type:204 ConstantPool:false Array:false}]}
class{name: datadog.ProfilerSetting, id: 16017, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:name Type:212 ConstantPool:false Array:false} {Name:value Type:212 ConstantPool:false Array:false} {Name:unit Type:212 ConstantPool:false Array:false}]}
class{name: datadog.SmapParseErrorEvent, id: 16037, fields: [{Name:startTime Type:204 ConstantPool:false Array:false} {Name:duration Type:204 ConstantPool:false Array:false} {Name:eventThread Type:162 ConstantPool:true Array:false} {Name:stackTrace Type:186 ConstantPool:true Array:false} {Name:reason Type:212 ConstantPool:false Array:false}]}
class{name: boolean, id: 4, fields: []}
class{name: char, id: 5, fields: []}
class{name: float, id: 6, fields: []}
class{name: double, id: 7, fields: []}
class{name: byte, id: 8, fields: []}
class{name: short, id: 9, fields: []}
class{name: int, id: 10, fields: []}
class{name: long, id: 11, fields: []}
class{name: java.lang.String, id: 20, fields: []}
class{name: java.lang.Class, id: 21, fields: [{Name:classLoader Type:23 ConstantPool:true Array:false} {Name:name Type:30 ConstantPool:true Array:false} {Name:package Type:29 ConstantPool:true Array:false} {Name:modifiers Type:10 ConstantPool:false Array:false}]}
class{name: java.lang.Thread, id: 22, fields: [{Name:osName Type:20 ConstantPool:false Array:false} {Name:osThreadId Type:11 ConstantPool:false Array:false} {Name:javaName Type:20 ConstantPool:false Array:false} {Name:javaThreadId Type:11 ConstantPool:false Array:false}]}
class{name: jdk.types.ClassLoader, id: 23, fields: [{Name:type Type:21 ConstantPool:true Array:false} {Name:name Type:30 ConstantPool:true Array:false}]}
class{name: jdk.types.FrameType, id: 24, fields: [{Name:description Type:20 ConstantPool:false Array:false}]}
class{name: jdk.types.ThreadState, id: 25, fields: [{Name:name Type:20 ConstantPool:false Array:false}]}
class{name: datadog.types.ExecutionMode, id: 33, fields: [{Name:name Type:20 ConstantPool:false Array:false}]}
class{name: jdk.types.StackTrace, id: 26, fields: [{Name:truncated Type:4 ConstantPool:false Array:false} {Name:frames Type:27 ConstantPool:false Array:true}]}
class{name: jdk.types.StackFrame, id: 27, fields: [{Name:method Type:28 ConstantPool:true Array:false} {Name:lineNumber Type:10 ConstantPool:false Array:false} {Name:bytecodeIndex Type:10 ConstantPool:false Array:false} {Name:type Type:24 ConstantPool:true Array:false}]}
class{name: jdk.types.Method, id: 28, fields: [{Name:type Type:21 ConstantPool:true Array:false} {Name:name Type:30 ConstantPool:true Array:false} {Name:descriptor Type:30 ConstantPool:true Array:false} {Name:modifiers Type:10 ConstantPool:false Array:false} {Name:hidden Type:4 ConstantPool:false Array:false}]}
class{name: jdk.types.Package, id: 29, fields: [{Name:name Type:30 ConstantPool:true Array:false}]}
class{name: jdk.types.Symbol, id: 30, fields: [{Name:string Type:20 ConstantPool:false Array:false}]}
class{name: profiler.types.LogLevel, id: 31, fields: [{Name:name Type:20 ConstantPool:false Array:false}]}
class{name: profiler.types.AttributeValue, id: 32, fields: [{Name:value Type:20 ConstantPool:false Array:false}]}
class{name: profiler.types.CounterName, id: 34, fields: [{Name:value Type:20 ConstantPool:false Array:false}]}

class{name: datadog.ExecutionSample, id: 101, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:eventThread Type:22 ConstantPool:true Array:false} {Name:stackTrace Type:26 ConstantPool:true Array:false} {Name:state Type:25 ConstantPool:true Array:false} {Name:mode Type:33 ConstantPool:true Array:false}
{Name:weight Type:11 ConstantPool:false Array:false} {Name:spanId Type:11 ConstantPool:false Array:false} {Name:localRootSpanId Type:11 ConstantPool:false Array:false} {Name:_dd.trace.operation Type:32 ConstantPool:true Array:false}]}

class{name: datadog.MethodSample, id: 102, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:eventThread Type:22 ConstantPool:true Array:false} {Name:stackTrace Type:26 ConstantPool:true Array:false} {Name:state Type:25 ConstantPool:true Array:false} {Name:mode Type:33 ConstantPool:true Array:false} {Name:weight Type:11 ConstantPool:false Array:false} {Name:spanId Type:11 ConstantPool:false Array:false} {Name:localRootSpanId Type:11 ConstantPool:false Array:false} {Name:_dd.trace.operation Type:32 ConstantPool:true Array:false}]}
class{name: datadog.WallClockSamplingEpoch, id: 118, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:duration Type:11 ConstantPool:false Array:false} {Name:samplePoolSize Type:10 ConstantPool:false Array:false} {Name:numSuccessfulSamples Type:10 ConstantPool:false Array:false} {Name:numFailedSamples Type:10 ConstantPool:false Array:false} {Name:numExitedThreads Type:10 ConstantPool:false Array:false} {Name:numPermissionDenied Type:10 ConstantPool:false Array:false}]}
class{name: datadog.ObjectSample, id: 103, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:eventThread Type:22 ConstantPool:true Array:false} {Name:stackTrace Type:26 ConstantPool:true Array:false} {Name:objectClass Type:21 ConstantPool:true Array:false} {Name:size Type:11 ConstantPool:false Array:false} {Name:weight Type:6 ConstantPool:false Array:false} {Name:spanId Type:11 ConstantPool:false Array:false} {Name:localRootSpanId Type:11 ConstantPool:false Array:false} {Name:_dd.trace.operation Type:32 ConstantPool:true Array:false}]}
class{name: datadog.HeapLiveObject, id: 105, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:eventThread Type:22 ConstantPool:true Array:false} {Name:stackTrace Type:26 ConstantPool:true Array:false} {Name:objectClass Type:21 ConstantPool:true Array:false} {Name:age Type:11 ConstantPool:false Array:false} {Name:size Type:11 ConstantPool:false Array:false} {Name:weight Type:6 ConstantPool:false Array:false} {Name:spanId Type:11 ConstantPool:false Array:false} {Name:localRootSpanId Type:11 ConstantPool:false Array:false} {Name:_dd.trace.operation Type:32 ConstantPool:true Array:false}]}
class{name: datadog.Endpoint, id: 119, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:duration Type:11 ConstantPool:false Array:false} {Name:eventThread Type:22 ConstantPool:true Array:false} {Name:stackTrace Type:26 ConstantPool:true Array:false} {Name:endpoint Type:20 ConstantPool:true Array:false} {Name:operation Type:32 ConstantPool:true Array:false} {Name:localRootSpanId Type:11 ConstantPool:false Array:false}]}
class{name: datadog.QueueTime, id: 123, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:duration Type:11 ConstantPool:false Array:false} {Name:eventThread Type:22 ConstantPool:true Array:false} {Name:origin Type:22 ConstantPool:true Array:false} {Name:task Type:21 ConstantPool:true Array:false} {Name:scheduler Type:21 ConstantPool:true Array:false} {Name:spanId Type:11 ConstantPool:false Array:false} {Name:localRootSpanId Type:11 ConstantPool:false Array:false} {Name:_dd.trace.operation Type:32 ConstantPool:true Array:false}]}
class{name: datadog.HeapUsage, id: 121, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:size Type:11 ConstantPool:false Array:false} {Name:isLive Type:4 ConstantPool:false Array:false}]}
class{name: jdk.CPULoad, id: 108, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:jvmUser Type:6 ConstantPool:false Array:false} {Name:jvmSystem Type:6 ConstantPool:false Array:false} {Name:machineTotal Type:6 ConstantPool:false Array:false}]}
class{name: jdk.ActiveRecording, id: 109, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:duration Type:11 ConstantPool:false Array:false} {Name:eventThread Type:22 ConstantPool:true Array:false} {Name:stackTrace Type:26 ConstantPool:true Array:false} {Name:id Type:11 ConstantPool:false Array:false} {Name:name Type:20 ConstantPool:false Array:false} {Name:destination Type:20 ConstantPool:false Array:false} {Name:maxAge Type:11 ConstantPool:false Array:false} {Name:flushInterval Type:11 ConstantPool:false Array:false} {Name:maxSize Type:11 ConstantPool:false Array:false} {Name:recordingStart Type:11 ConstantPool:false Array:false} {Name:recordingDuration Type:11 ConstantPool:false Array:false}]}
class{name: jdk.ActiveSetting, id: 110, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:duration Type:11 ConstantPool:false Array:false} {Name:eventThread Type:22 ConstantPool:true Array:false} {Name:stackTrace Type:26 ConstantPool:true Array:false} {Name:id Type:11 ConstantPool:false Array:false} {Name:name Type:20 ConstantPool:false Array:false} {Name:value Type:20 ConstantPool:false Array:false}]}
class{name: datadog.ProfilerSetting, id: 120, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:duration Type:11 ConstantPool:false Array:false} {Name:eventThread Type:22 ConstantPool:true Array:false} {Name:stackTrace Type:26 ConstantPool:true Array:false} {Name:name Type:20 ConstantPool:false Array:false} {Name:value Type:20 ConstantPool:false Array:false} {Name:unit Type:20 ConstantPool:false Array:false}]}
class{name: datadog.DatadogProfilerConfig, id: 122, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:duration Type:11 ConstantPool:false Array:false} {Name:eventThread Type:22 ConstantPool:true Array:false} {Name:cpuInterval Type:11 ConstantPool:false Array:false} {Name:wallInterval Type:11 ConstantPool:false Array:false} {Name:allocInterval Type:11 ConstantPool:false Array:false} {Name:memleakInterval Type:11 ConstantPool:false Array:false} {Name:memleakCapacity Type:11 ConstantPool:false Array:false} {Name:memleakTrackPercent Type:11 ConstantPool:false Array:false} {Name:gcGenerations Type:4 ConstantPool:false Array:false} {Name:modeMask Type:10 ConstantPool:false Array:false} {Name:version Type:20 ConstantPool:false Array:false} {Name:cpuEngine Type:20 ConstantPool:false Array:false}]}
class{name: datadog.DatadogProfilerClassRefCache, id: 124, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:size Type:11 ConstantPool:false Array:false}]}
class{name: datadog.ProfilerCounter, id: 125, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:name Type:34 ConstantPool:false Array:false} {Name:count Type:11 ConstantPool:false Array:false}]}
class{name: jdk.OSInformation, id: 111, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:osVersion Type:20 ConstantPool:false Array:false}]}
class{name: jdk.CPUInformation, id: 112, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:cpu Type:20 ConstantPool:false Array:false} {Name:description Type:20 ConstantPool:false Array:false} {Name:sockets Type:10 ConstantPool:false Array:false} {Name:cores Type:10 ConstantPool:false Array:false} {Name:hwThreads Type:10 ConstantPool:false Array:false}]}
class{name: jdk.JVMInformation, id: 114, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:jvmName Type:20 ConstantPool:false Array:false} {Name:jvmVersion Type:20 ConstantPool:false Array:false} {Name:jvmArguments Type:20 ConstantPool:false Array:false} {Name:jvmFlags Type:20 ConstantPool:false Array:false} {Name:javaArguments Type:20 ConstantPool:false Array:false} {Name:jvmStartTime Type:11 ConstantPool:false Array:false} {Name:pid Type:11 ConstantPool:false Array:false}]}
class{name: jdk.InitialSystemProperty, id: 115, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:key Type:20 ConstantPool:false Array:false} {Name:value Type:20 ConstantPool:false Array:false}]}
class{name: jdk.NativeLibrary, id: 116, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:name Type:20 ConstantPool:false Array:false} {Name:baseAddress Type:11 ConstantPool:false Array:false} {Name:topAddress Type:11 ConstantPool:false Array:false}]}
class{name: profiler.Log, id: 117, fields: [{Name:startTime Type:11 ConstantPool:false Array:false} {Name:level Type:31 ConstantPool:true Array:false} {Name:message Type:20 ConstantPool:false Array:false}]}
class{name: jdk.jfr.Label, id: 201, fields: [{Name:value Type:20 ConstantPool:false Array:false}]}
class{name: jdk.jfr.Category, id: 202, fields: [{Name:value Type:20 ConstantPool:false Array:true}]}
class{name: jdk.jfr.Timestamp, id: 203, fields: [{Name:value Type:20 ConstantPool:false Array:false}]}
class{name: jdk.jfr.Timespan, id: 204, fields: [{Name:value Type:20 ConstantPool:false Array:false}]}
class{name: jdk.jfr.DataAmount, id: 205, fields: [{Name:value Type:20 ConstantPool:false Array:false}]}
class{name: jdk.jfr.MemoryAddress, id: 206, fields: []}
class{name: jdk.jfr.Unsigned, id: 207, fields: []}
class{name: jdk.jfr.Percentage, id: 208, fields: []}

*/
