package jdk8

const (
	// JDK9And10Prefix The prefix used for JDK 9 and 10.
	JDK9And10Prefix    = "com.oracle.jdk."
	EventIdRoot        = "http://www.oracle.com/hotspot/"
	JvmEventIdRoot     = EventIdRoot + "jvm/"
	JdkEventIdRoot     = EventIdRoot + "jdk/"
	JFRInfoEventIdRoot = EventIdRoot + "jfr-info/"
)

// JDK8 type id constants
const (
	CpuLoad                            = JvmEventIdRoot + "os/processor/cpu_load"
	ExecutionSample                    = JvmEventIdRoot + "vm/prof/execution_sample"
	ExecutionSamplingInfoEventId       = JvmEventIdRoot + "vm/prof/execution_sampling_info"
	Processes                          = JvmEventIdRoot + "os/system_process"
	OsMemorySummary                    = JvmEventIdRoot + "os/memory/physical_memory"
	OsInformation                      = JvmEventIdRoot + "os/information"
	CpuInformation                     = JvmEventIdRoot + "os/processor/cpu_information"
	ThreadAllocationStatistics         = JvmEventIdRoot + "java/statistics/thread_allocation"
	HeapConf                           = JvmEventIdRoot + "vm/gc/configuration/heap"
	GcConf                             = JvmEventIdRoot + "vm/gc/configuration/gc"
	HeapSummary                        = JvmEventIdRoot + "vm/gc/heap/summary"
	AllocInsideTlab                    = JvmEventIdRoot + "java/object_alloc_in_new_TLAB"
	AllocOutsideTlab                   = JvmEventIdRoot + "java/object_alloc_outside_TLAB"
	VmInfo                             = JvmEventIdRoot + "vm/info"
	ClassLoad                          = JvmEventIdRoot + "vm/class/load"
	ClassUnload                        = JvmEventIdRoot + "vm/class/unload"
	ClassLoadStatistics                = JvmEventIdRoot + "java/statistics/class_loading"
	Compilation                        = JvmEventIdRoot + "vm/compiler/compilation"
	FileWrite                          = JdkEventIdRoot + "java/file_write"
	FileRead                           = JdkEventIdRoot + "java/file_read"
	SocketWrite                        = JdkEventIdRoot + "java/socket_write"
	SocketRead                         = JdkEventIdRoot + "java/socket_read"
	ThreadPark                         = JvmEventIdRoot + "java/thread_park"
	ThreadSleep                        = JvmEventIdRoot + "java/thread_sleep"
	MonitorEnter                       = JvmEventIdRoot + "java/monitor_enter"
	MonitorWait                        = JvmEventIdRoot + "java/monitor_wait"
	MetaspaceOom                       = JvmEventIdRoot + "vm/gc/metaspace/out_of_memory"
	CodeCacheFull                      = JvmEventIdRoot + "vm/code_cache/full"
	CodeCacheStatistics                = JvmEventIdRoot + "vm/code_cache/stats"
	CodeSweeperStatistics              = JvmEventIdRoot + "vm/code_sweeper/stats"
	SweepCodeCache                     = JvmEventIdRoot + "vm/code_sweeper/sweep"
	EnvironmentVariable                = JvmEventIdRoot + "os/initial_environment_variable"
	SystemProperties                   = JvmEventIdRoot + "vm/initial_system_property"
	ObjectCount                        = JvmEventIdRoot + "vm/gc/detailed/object_count"
	GcReferenceStatistics              = JvmEventIdRoot + "vm/gc/reference/statistics"
	OldObjectSample                    = JvmEventIdRoot + "java/old_object"
	GcPauseL3                          = JvmEventIdRoot + "vm/gc/phases/pause_level_3"
	GcPauseL2                          = JvmEventIdRoot + "vm/gc/phases/pause_level_2"
	GcPauseL1                          = JvmEventIdRoot + "vm/gc/phases/pause_level_1"
	GcPause                            = JvmEventIdRoot + "vm/gc/phases/pause"
	MetaspaceSummary                   = JvmEventIdRoot + "vm/gc/heap/metaspace_summary"
	GarbageCollection                  = JvmEventIdRoot + "vm/gc/collector/garbage_collection"
	ConcurrentModeFailure              = JvmEventIdRoot + "vm/gc/detailed/concurrent_mode_failure"
	ThrowablesStatistics               = JdkEventIdRoot + "java/statistics/throwables"
	ErrorsThrown                       = JdkEventIdRoot + "java/error_throw"
	ExceptionsThrown                   = JdkEventIdRoot + "java/exception_throw"
	CompilerStats                      = JvmEventIdRoot + "vm/compiler/stats"
	CompilerFailure                    = JvmEventIdRoot + "vm/compiler/failure"
	UlongFlag                          = JvmEventIdRoot + "vm/flag/ulong"
	BooleanFlag                        = JvmEventIdRoot + "vm/flag/boolean"
	StringFlag                         = JvmEventIdRoot + "vm/flag/string"
	DoubleFlag                         = JvmEventIdRoot + "vm/flag/double"
	LongFlag                           = JvmEventIdRoot + "vm/flag/long"
	IntFlag                            = JvmEventIdRoot + "vm/flag/int"
	UintFlag                           = JvmEventIdRoot + "vm/flag/uint"
	UlongFlagChanged                   = JvmEventIdRoot + "vm/flag/ulong_changed"
	BooleanFlagChanged                 = JvmEventIdRoot + "vm/flag/boolean_changed"
	StringFlagChanged                  = JvmEventIdRoot + "vm/flag/string_changed"
	DoubleFlagChanged                  = JvmEventIdRoot + "vm/flag/double_changed"
	LongFlagChanged                    = JvmEventIdRoot + "vm/flag/long_changed"
	IntFlagChanged                     = JvmEventIdRoot + "vm/flag/int_changed"
	UintFlagChanged                    = JvmEventIdRoot + "vm/flag/uint_changed"
	TimeConversion                     = JvmEventIdRoot + "os/processor/cpu_tsc"
	ThreadDump                         = JvmEventIdRoot + "vm/runtime/thread_dump"
	GcConfYoungGeneration              = JvmEventIdRoot + "vm/gc/configuration/young_generation"
	GcConfSurvivor                     = JvmEventIdRoot + "vm/gc/configuration/survivor"
	GcConfTlab                         = JvmEventIdRoot + "vm/gc/configuration/tlab"
	JavaThreadStart                    = JvmEventIdRoot + "java/thread_start"
	JavaThreadEnd                      = JvmEventIdRoot + "java/thread_end"
	VmOperations                       = JvmEventIdRoot + "vm/runtime/execute_vm_operation"
	ThreadStatistics                   = JvmEventIdRoot + "java/statistics/threads"
	ContextSwitchRate                  = JvmEventIdRoot + "os/processor/context_switch_rate"
	CompilerConfig                     = JvmEventIdRoot + "vm/compiler/config"
	CodeCacheConfig                    = JvmEventIdRoot + "vm/code_cache/config"
	CodeSweeperConfig                  = JvmEventIdRoot + "vm/code_sweeper/config"
	CompilerPhase                      = JvmEventIdRoot + "vm/compiler/phase"
	GcCollectorG1GarbageCollection     = JvmEventIdRoot + "vm/gc/collector/g1_garbage_collection"
	GcCollectorOldGarbageCollection    = JvmEventIdRoot + "vm/gc/collector/old_garbage_collection"
	GcCollectorParoldGarbageCollection = JvmEventIdRoot + "vm/gc/collector/parold_garbage_collection"
	GcCollectorYoungGarbageCollection  = JvmEventIdRoot + "vm/gc/collector/young_garbage_collection"
	GcDetailedAllocationRequiringGc    = JvmEventIdRoot + "vm/gc/detailed/allocation_requiring_gc"
	GcDetailedEvacuationFailed         = JvmEventIdRoot + "vm/gc/detailed/evacuation_failed"
	GcDetailedEvacuationInfo           = JvmEventIdRoot + "vm/gc/detailed/evacuation_info"
	GcDetailedObjectCountAfterGc       = JvmEventIdRoot + "vm/gc/detailed/object_count_after_gc"
	GcDetailedPromotionFailed          = JvmEventIdRoot + "vm/gc/detailed/promotion_failed"
	GcHeapPsSummary                    = JvmEventIdRoot + "vm/gc/heap/ps_summary"
	GcMetaspaceAllocationFailure       = JvmEventIdRoot + "vm/gc/metaspace/allocation_failure"
	GcMetaspaceChunkFreeListSummary    = JvmEventIdRoot + "vm/gc/metaspace/chunk_free_list_summary"
	GcMetaspaceGcThreshold             = JvmEventIdRoot + "vm/gc/metaspace/gc_threshold"

	RECORDINGS             = JFRInfoEventIdRoot + "recordings/recording"
	RecordingSetting       = JFRInfoEventIdRoot + "recordings/recording_setting"
	JDK9_RECORDING_SETTING = JDK9And10Prefix + "ActiveSetting"

	GcG1mmu = JDK9And10Prefix + "GCG1MMU"
)
